Migrate from Forestry to TinaCMS [RAM-252]
red-ant/redant-home pull request #307
Opened 2023-01-25 06:07 UTC by DigitalSuey

2023-02-07 22:42 UTC, DigitalSuey commented
⚠️ Don't forget to rebase and make sure the new pages work locally before merging

2023-02-10 03:59 UTC, jsntv200 requested changes
Im inclined to split this into 2 PR's. The first is just the markdown changes, these are dafe to go and probably good to merge. The second PR would be just the TinaCMS stuff if we decide to go with it.

2023-02-10 03:59 UTC, jsntv200 commented on CNAME
> +staging.redant.com.au
Remember to set this back to redant.com.au

2023-02-10 03:59 UTC, jsntv200 commented on .github/workflows/build-and-deploy.yml
> +# This workflow uses actions that are not certified by GitHub.
Rebase against master to remove this file which is already in master

2023-02-12 22:06 UTC, DigitalSuey commented on .github/workflows/build-and-deploy.yml
> +# This workflow uses actions that are not certified by GitHub.
Fixed in [750d657](https://github.com/red-ant/redant-home/pull/307/commits/750d657502d392cf47bf9d186bc35ae0009bc17f)

2023-02-12 22:09 UTC, jsntv200 reviewed
All good, just the CNAME to revert.

Don't bother with it for the moment but the config.js got pretty big. Might be worth splitting that out into individual files like the old front_matter templates then load and merge into config.

2023-02-12 22:29 UTC, DigitalSuey commented
All markdown changes were moved to https://github.com/red-ant/redant-home/pull/311

2023-02-22 22:58 UTC, DigitalSuey commented on CNAME
> +staging.redant.com.au
Done in [de86fd4](https://github.com/red-ant/redant-home/pull/307/commits/de86fd4919ea22cbe7ee15c8fc1ff01c852a1d3b)

2023-02-22 23:26 UTC, DigitalSuey commented
**Note:** Forestry.io end of life is on 22/03/2023

2023-03-24 04:38 UTC, merged